/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoadQuizIndexRouteImport } from './routes/load-quiz.index'
import { Route as Build_quizQuizIdRouteImport } from './routes/build_quiz.$quizId'
import { Route as PlayQuizIdAttemptAttemptIdRouteImport } from './routes/play.$quizId.attempt.$attemptId'

const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadQuizIndexRoute = LoadQuizIndexRouteImport.update({
  id: '/load-quiz/',
  path: '/load-quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const Build_quizQuizIdRoute = Build_quizQuizIdRouteImport.update({
  id: '/build_quiz/$quizId',
  path: '/build_quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizIdAttemptAttemptIdRoute =
  PlayQuizIdAttemptAttemptIdRouteImport.update({
    id: '/play/$quizId/attempt/$attemptId',
    path: '/play/$quizId/attempt/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/build_quiz/$quizId': typeof Build_quizQuizIdRoute
  '/load-quiz/': typeof LoadQuizIndexRoute
  '/play/$quizId/attempt/$attemptId': typeof PlayQuizIdAttemptAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/build_quiz/$quizId': typeof Build_quizQuizIdRoute
  '/load-quiz': typeof LoadQuizIndexRoute
  '/play/$quizId/attempt/$attemptId': typeof PlayQuizIdAttemptAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/build_quiz/$quizId': typeof Build_quizQuizIdRoute
  '/load-quiz/': typeof LoadQuizIndexRoute
  '/play/$quizId/attempt/$attemptId': typeof PlayQuizIdAttemptAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/500'
    | '/build_quiz/$quizId'
    | '/load-quiz/'
    | '/play/$quizId/attempt/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/500'
    | '/build_quiz/$quizId'
    | '/load-quiz'
    | '/play/$quizId/attempt/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/500'
    | '/build_quiz/$quizId'
    | '/load-quiz/'
    | '/play/$quizId/attempt/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  Build_quizQuizIdRoute: typeof Build_quizQuizIdRoute
  LoadQuizIndexRoute: typeof LoadQuizIndexRoute
  PlayQuizIdAttemptAttemptIdRoute: typeof PlayQuizIdAttemptAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load-quiz/': {
      id: '/load-quiz/'
      path: '/load-quiz'
      fullPath: '/load-quiz/'
      preLoaderRoute: typeof LoadQuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build_quiz/$quizId': {
      id: '/build_quiz/$quizId'
      path: '/build_quiz/$quizId'
      fullPath: '/build_quiz/$quizId'
      preLoaderRoute: typeof Build_quizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$quizId/attempt/$attemptId': {
      id: '/play/$quizId/attempt/$attemptId'
      path: '/play/$quizId/attempt/$attemptId'
      fullPath: '/play/$quizId/attempt/$attemptId'
      preLoaderRoute: typeof PlayQuizIdAttemptAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  R500Route: R500Route,
  Build_quizQuizIdRoute: Build_quizQuizIdRoute,
  LoadQuizIndexRoute: LoadQuizIndexRoute,
  PlayQuizIdAttemptAttemptIdRoute: PlayQuizIdAttemptAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
