/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayQuizIdRouteImport } from './routes/play.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizIdRoute = PlayQuizIdRouteImport.update({
  id: '/play/$quizId',
  path: '/play/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$quizId': typeof PlayQuizIdRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$quizId': typeof PlayQuizIdRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$quizId': typeof PlayQuizIdRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$quizId' | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$quizId' | '/play'
  id: '__root__' | '/' | '/play/$quizId' | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayQuizIdRoute: typeof PlayQuizIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$quizId': {
      id: '/play/$quizId'
      path: '/play/$quizId'
      fullPath: '/play/$quizId'
      preLoaderRoute: typeof PlayQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayQuizIdRoute: PlayQuizIdRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
